add sequential execution mode option
stepci/runner pull request #103
Opened 2023-03-28 13:06 UTC by yu-fuku

discussion https://github.com/stepci/stepci/discussions/122
stepci https://github.com/stepci/stepci/pull/123

2023-03-28 13:36 UTC, mishushakov commented
I believe some users would prefer more control over the concurrency (eg. 1 to Infinity)
I'd say this should be a workflow-level setting

Have a look at p-map by sindresorhus

https://github.com/sindresorhus/p-map

Maybe refactor the `run` function accordingly?

2023-03-28 13:37 UTC, mishushakov commented
Btw. we sindre has moved all his packages to ESM modules, which we don't support. If you see a related error, just install an older version of p-map

2023-03-29 11:15 UTC, yu-fuku commented
Thanks for checking and answering.

>I believe some users would prefer more control over the concurrency (eg. 1 to Infinity)

I'd prefer to have user control, as you say.

Let me ask you a few questions

1.
> Also this should be a workflow-level setting,
Am I correct in understanding that the file specified in the include syntax is the target?
(I think only one workflow will work unless you specify multiple files in the include)

For example, for the following workflow files, allow the user to choose which of the included files to execute sequentially or in concurrency?

```
version: "1.1"
name: Status Check
include:
  - sequentially_1.yml
  - sequentially_2.yml
  - concurrency.yml
```
sequentially_1.yml and sequentially_2.yml are executed sequentially (sequentially_2.yml is executed when sequentially_1yml is completed)
concurrency.yml is parallel execution
Allow users to select files to run sequentially on a file-by-file basis?

2.
>with an option to overwrite from CLI

What value do you expect to input from CLI as option?
(Name of files you want to run sequentially(or concurrency)?)
I'm sorry, I can't imagine much about the content of this answer.

2023-03-29 11:23 UTC, mishushakov commented
Workflow level:

```yaml
version: "1.1"
name: Status Check
config:
  concurrency: 3 # Run 3 tests concurrently
include:
  - 1.yml
  - 2.yml
  - 3.yml
```

CLI option:

```
stepci run workflow.yml --concurrency=3
```

Hope this helps. Let me know if you need more

2023-03-29 11:23 UTC, mishushakov commented
When `config.concurency` is not specified it should default to Infinite

2023-03-29 11:27 UTC, mishushakov commented
There's also this library, which is similar to p-map:
https://www.npmjs.com/package/p-limit

2023-03-30 04:01 UTC, yu-fuku commented
Thanks for replay.
Your answers are so helpful.

You mean to allow parallel execution of included files with specified number of parallel.

Please give me a few days to fix the current implementation and update the pull request.

2023-03-30 10:03 UTC, mishushakov commented
Of course! Glad to help further.

Don't feel pressured though. In open-source you can contribute at your own pace 😎

2023-04-12 14:48 UTC, mishushakov commented
Hi, @yu-fuku 
Any progress? Let me know if you're stuck and need any help 😁

2023-04-15 08:55 UTC, yu-fuku commented
Sorry it took so long to respond.

The number of parallel executions can now be controlled using p-limt.
Please check and comment.

2023-04-15 10:35 UTC, mishushakov commented
No worries! Glad you took your time to update the pull request.

Have you verified it works?

2023-04-18 04:37 UTC, yu-fuku commented
Yes. I have confirmed the following operation.

1, No config.concurrency or cli arguments set → confirm that everything runs in parallel
2, Parallel execution with the number of executions set in config.concurrency
3, Parallel execution with the value set in the cli argument(highest priority)

2023-04-18 06:43 UTC, mishushakov commented
If you set it to 0 does it run in a sequence?

2023-04-18 07:34 UTC, yu-fuku commented
Sorry I didn't check when I put the 0 in.

p-limit did not seem to accept values less than 0
https://github.com/sindresorhus/p-limit/blob/v3.1.0/index.js#L5

So I modified runner so that it is executed sequentially when a value less than or equal to 0 is entered.
Please check and comment.

I confirmed that when I incorporate this modification and enter 0, sequential execution is being performed.

2023-04-18 15:20 UTC, mishushakov requested changes
Pretty much there (thanks for updating the pull request). I have very small changes to suggest 😄

2023-04-18 15:20 UTC, mishushakov commented on src/index.ts
> +  if(workflow.config?.concurrency || workflow.config?.concurrency == 0) {
remove the `workflow.config?.concurrency == 0` condition

2023-04-18 15:20 UTC, mishushakov commented on src/index.ts
> +  let limit = pLimit(concurrency_num)
`let` should be `const`

2023-05-24 10:10 UTC, mishushakov commented
Hello, let me know if you have any updates?

2023-06-05 01:02 UTC, fu-yuta commented
sorry I wasn't able to respond to your comment
I have responded now, so could you please check?

2023-06-05 18:18 UTC, mishushakov commented
No worries, merging it!

2023-06-05 18:18 UTC, merged