Feature/multipart form data content type
stepci/runner pull request #116
Opened 2024-05-21 12:11 UTC by blagerweij

Added support for 'Content-Type' for multipart requests:

```
          formData:
            foo: bar
            patient:
              value: '{"reference":"a97a62d5-9f33-470d-aa05-d39ed3570105", "name": "john doe" }'
              type: application/json
            payer:
              file: bla.pdf
              type: application/pdf
```

Results in:
```
POST /post HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="patient"; filename="bla.json"
Content-Type: application/json

{"reference":"a97a62d5-9f33-470d-aa05-d39ed3570105", "name": "john doe" }
--WebAppBoundary
Content-Disposition: form-data; name="payer"; filename="bla.pdf"
Content-Type: application/pdf
```

2024-05-22 08:01 UTC, blagerweij commented
@mishushakov we need this feature to run our tests, since we use json form-data fields. Could you please review the PR?

2024-06-05 09:38 UTC, mishushakov commented
Looks good to me, see my comments. Can I also ask you to update the documentation after it has been merged?

2024-06-05 13:42 UTC, mishushakov requested changes

2024-06-05 15:56 UTC, blagerweij commented
@mishushakov requested changes applied, although that means having to duplicate the call to `formData.append`.... Please have a look.

2024-06-05 16:52 UTC, merged